# Generated by Django 3.2.8 on 2021-11-03 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_remove_user_middle_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='streaming_providers',
            field=models.JSONField(default=[]),
        ),
    ]
