# Generated by Django 3.2.8 on 2021-11-03 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_watchedshows_watchlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchedshows',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='watchedshows',
            name='user_rating',
            field=models.BooleanField(default=False),
        ),
    ]
