# Generated by Django 3.2.8 on 2021-11-10 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchedshows',
            name='user_rating',
            field=models.BooleanField(null=True),
        ),
    ]
