# Generated by Django 3.2.8 on 2021-11-10 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0002_alter_watchedshows_user_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watchedshows',
            old_name='user_rating',
            new_name='user_liked',
        ),
        migrations.RemoveField(
            model_name='watchedshows',
            name='tv_show',
        ),
        migrations.RemoveField(
            model_name='watchlist',
            name='tv_show',
        ),
        migrations.AddField(
            model_name='watchedshows',
            name='tv_show_data',
            field=models.JSONField(default=dict),
        ),
    ]
