# Generated by Django 3.2.8 on 2021-11-10 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0003_auto_20211110_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchedshows',
            name='tv_show_data',
            field=models.JSONField(default=list),
        ),
    ]
