# Generated by Django 3.2.8 on 2021-11-10 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0004_alter_watchedshows_tv_show_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchedshows',
            name='tv_show_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
