# Generated by Django 3.2.8 on 2021-11-10 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0005_watchedshows_tv_show_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='tv_show_data',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='watchlist',
            name='tv_show_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
