# Generated by Django 3.2.8 on 2021-11-10 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0006_auto_20211110_1151'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watchedshows',
            old_name='user_liked',
            new_name='liked_show',
        ),
    ]
